import type { Metadata } from "next";

import FooterSection from "@/components/Footer";
import Navbar from "@/components/NAVBAR";
import "./globals.css";

export const metadata: Metadata = {
  title: "shakeelintl",
  description: "Generated by zaki",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
